# Generated by Django 5.2 on 2025-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_avatar_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='qq.jpg', null=True, upload_to=''),
        ),
    ]
